model_name: 'ae_single_rgb_v0'

experiment:
  seed: 1

model:
  autoencoder: true
  img_size: 256
  input_channels: 3
  flow: false
  stack_k: null
  max_horizon_mins: null
  base_model: 'ResNet50'
  sequence: 'SingleRGB'
  use_diffs: false
  num_classes: 4
  top_dropout: 0.3
  target_names:
    - 'low'
    - 'mid'
    - 'high'
    - 'flood'

train:
  optimizer: 'adam'
  lr: 0.01
  sgd_momentum: 0.9
  use_augments: true
  augmentations:
    - 'rotation'
    - 'translation'
    - 'zoom'
    - 'contrast'
  weights: 'imagenet'
  finetune: false
  loss: 'mse'
  batch_size: 8 
  epochs: 50
  samples_class_train: 2000
  max_samples_class_valid: 1000
  keep_ckpts: 3
  workers: 8

eval:
  metrics:
    - 'mae'
  batch_size: 8
  workers: 8

paths:
  csv_path: '/workspace/resources/flood_images_annot.csv'
  enoe_dir: '/enoe'
  flow_dir: '/flow'
  models_dir: '/models'

