model_name: 'baseline_v1'

experiment:
  seed: 1

model:
  img_size: 224
  input_channels: 3
  flow: false
  base_model: 'ResNet50'
  sequence: 'SingleRGB'
  num_classes: 4
  top_dropout: 0.3
  target_names:
    - 'low'
    - 'mid'
    - 'high'
    - 'flood'

train:
  optimizer: 'adam'
  lr: 0.01
  sgd_momentum: 0.9
  use_augments: true
  augmentations:
    - 'rotation'
    - 'translation'
    - 'zoom'
    - 'contrast'
  weights: 'imagenet'
  finetune: false
  loss: 'categorical_crossentropy'
  batch_size: 32  
  epochs: 50
  samples_class_train: 2000
  max_samples_class_valid: 1000
  keep_ckpts: 3
  workers: 8

eval:
  metrics:
    - 'accuracy'
  batch_size: 32
  workers: 8

paths:
  csv_path: '/workspace/resources/flood_images_annot.csv'
  data_dir: '/enoe'
  models_dir: '/models'

