model_name: 'baseline_v0'

experiment:
  seed: 1

model:
  img_size: 224
  flow: false
  base_model: 'ResNet50'
  sequence: 'SingleRGB'
  num_classes: 4
  top_dropout: 0.3
  target_names:
    - 'low'
    - 'mid'
    - 'high'
    - 'flood'

train:
  optimizer: 'sgd'
  lr: 0.01
  decay_steps: 10000
  decay_rate: 0.96
  sgd_momentum: 0.9
  use_augments: true
  weights: 'imagenet'
  finetune: false
  loss: 'categorical_crossentropy'
  batch_size: 32  
  epochs: 40
  workers: 8

eval:
  metrics:
    - 'accuracy'
  batch_size: 32

paths:
  csv_path: '/workspace/resources/flood_images_annot.csv'
  data_dir: '/enoe'
  models_dir: '/models'
