model_name: 'baseline_v1'

experiment:
  seed: 1
  split: 2

model:
  img_size: 224
  flow: false
  base_model: 'EfficientNetB0'
  sequence: 'SingleRBG'
  num_classes: 4
  top_dropout: 0.3
  target_names:
    - 'low'
    - 'mid'
    - 'high'
    - 'flood'

train:
  lr: 0.01
  optimizer: 'adam'
  use_augments: true
  weights: 'imagenet'
  finetune: false
  loss: 'categorical_crossentropy'
  batch_size: 32  
  epochs: 40
  workers: 8

eval:
  metrics:
    - 'accuracy'
  batch_size: 32

paths:
  csv_path: '/workspace/resources/flood_images_annot.csv'
  data_dir: '/enoe'
  models_dir: '/models'
